### ISSUE TITLE
Can't use with JavaScriptServices app

### ISSUE THREAD

**Issue by flightlevel** [MarkPieszak/angular-application-insights#15]
I'm sure the 'issue' here is the end user, but unsure where I'm going wrong
Using the https://github.com/aspnet/JavaScriptServices starter

Running Angular 4.1.2 with 2.0.0 version of angular-application-insights

This is my `app.module.client.ts`

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { sharedConfig } from './app.module.shared';
import { SharedService } from './services/shared.service';
import { ApplicationInsightsModule, AppInsightsService } from '@markpieszak/ng-application-insights';

@NgModule({
    bootstrap: sharedConfig.bootstrap,
    declarations: sharedConfig.declarations,
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        ApplicationInsightsModule.forRoot({
            instrumentationKey: 'key-removed-for-github'
        }),
        ...sharedConfig.imports
    ],
    providers: [
        { provide: 'ORIGIN_URL', useValue: location.origin }, SharedService, AppInsightsService
    ]
})
export class AppModule {
}
```

And this is the console error I get in Chrome

```
Angular application insights Error [downloadAndSetup]:  TypeError: applicationinsights_js_1.AppInsights.downloadAndSetup is not a function
    at AppInsightsService.init (main-client.js:1481)
    at new ApplicationInsightsModule (main-client.js:1281)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:262)
    at AppModuleInjector.NgModuleInjector.create (vendor.js:14073)
    at NgModuleFactory.create (vendor.js:14046)
    at vendor.js:15287
    at ZoneDelegate.invoke (vendor.js:83283)
    at Object.onInvoke (vendor.js:14664)
    at ZoneDelegate.invoke (vendor.js:83282)
    at Zone.run (vendor.js:83043)
```

Any ideas?

**Comment by MarkPieszak** [comment]
Haven't tried it with that first basic angular4 integration, does this happen right on page load?

**Comment by MarkPieszak** [comment]
https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/329#issuecomment-313381570

Thanks to @marchel2 for posting it

> Make sure you are calling the injector to get `AppInsightsService` during **ngOnInit**:

```typescript
export class HomeComponent implements OnInit {

    private AIService: AppInsightsService;
    private isBrowser: boolean;

    constructor( @Inject(PLATFORM_ID) private platformId, private injector: Injector) {
        this.isBrowser = isPlatformBrowser(this.platformId);
    }

    ngOnInit() {
        if (this.isBrowser) {
            this.AIService = <AppInsightsService>this.injector.get(AppInsightsService);
            this.AIService.trackEvent('Testing', { 'user': 'me' });
        } 
    }
}
```

**Comment by MarkPieszak** [comment]
This should be fixed now, the readme also showcases how to use it with JavascriptServices or my companion repo. Hope that helps!

**Comment by dominikfoldi** [comment]
I am trying to use the library with the dotnet angular template provided by the aspnet templating team.

I did everything exactly as stated in the [documentation](https://github.com/MarkPieszak/angular-application-insights#usage-with-aspnetcore-angular2-universal-repo-or-javascriptservices--apps-w-server-side-rendering-).
I have a shared AppModule and one for the server and another one for the browser. During ssr only the server one and the shared one used. I load the appinsights module in the browser AppModule.
I am injecting the AppInsightsService through the injector only if it is running in the browser.

Still, I get an error during prerendering: `Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering failed because of error: ReferenceError: define is not defined`

The problem occurs at `applicationinsights-js\bundle\ai.module.js:187:1`, so this line:
`define("JavaScriptSDK.Module/AppInsightsModule", ["require", "exports"], function (require, exports)`.

I have tried the https://github.com/MarkPieszak/aspnetcore-angular2-universal starter project and it works fine with this module, but I have to use the other template.

Do you have any idea how to resolve this?
